on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 19 ]
    name: Java ${{ matrix.java }}
    steps:
    - name: Setup Java Development Kits built by Oracle
      uses: oracle-actions/setup-java@v1.3.0
      with:
    	website: oracle.com
    	release: 19

    - name: Build with Maven
      run: mvn -B package

    - name: Execute JUnit 5 integration tests with Maven
      run: mvn -B test --file pom.xml
        
