on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 19 ]
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Build and Execute JUnit 5 integration tests with Maven
        run: |
          mvn -B package
          mvn -B test --file pom.xml
